# Generated by Django 5.2.1 on 2025-06-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name_plural': 'PostImages'},
        ),
    ]
