# Generated by Django 5.2.1 on 2025-06-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_post_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
