# Generated by Django 5.2.1 on 2025-06-24 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_postimages_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='members',
            field=models.ManyToManyField(null=True, related_name='channels', through='group.ChannelsMemberShip', to=settings.AUTH_USER_MODEL),
        ),
    ]
