# Generated by Django 5.2.1 on 2025-06-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_channels_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='image',
            field=models.ImageField(null=True, upload_to='channels/'),
        ),
    ]
