# Generated by Django 5.2.1 on 2025-06-26 10:19

import group.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_channels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='image',
            field=models.ImageField(default=group.models.get_default_channel_images, null=True, upload_to='channels/'),
        ),
    ]
