# Generated by Django 5.2.1 on 2025-06-27 15:32

import group.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='image',
            field=models.ImageField(blank=True, default=group.models.get_default_channel_images, null=True, upload_to='channels/'),
        ),
    ]
